### ISSUE TITLE
deploying wordpress service gives error "provider properties must be strings"

### ISSUE THREAD

**Issue by adaniline-traderev** [pulumi/kubernetes-the-prod-way#17] opened 2019-02-20 18:36 UTC
Trying to deploy wordpress service, got an error :"provider properties must be strings", this is most likely because kubeconfig output of infrastructure stack is a JSON object?

**Comment by kevintest711** [comment] 2019-02-20 18:58
Here is the output from pulumi up.

```
/kubernetes-the-prod-way/services/wordpress# pulumi up
Previewing update (wordpress):

     Type                             Name                                 Plan       Info
 +   pulumi:pulumi:Stack              wordpress-wordpress                  create     
 +   ├─ kubernetes:helm.sh:Chart      wpdev                                create     
 >-  ├─ pulumi:pulumi:StackReference  kevintest/infrastructure/kc-infra  read       
     └─ pulumi:providers:kubernetes   kevintest/infrastructure/kc-infra             1 error
 
Diagnostics:
  pulumi:providers:kubernetes (kevintest711/infrastructure/kc-ifra):
    error: pulumi:providers:kubernetes resource 'kevintest711/infrastructure/kc-ifra's property 'kubeconfig' value {map[apiVersion:{v1} clusters:{[{map[cluster:{map[certificate-authority-data:{CERT-REDACTED} server:{https://something.something.us-east-2.eks.amazonaws.com}]} name:{kubernetes}]}]} contexts:{[{map[context:{map[cluster:{kubernetes} user:{aws}]} name:{aws}]}]} current-context:{aws} kind:{Config} users:{[{map[name:{aws} user:{map[exec:{map[apiVersion:{client.authentication.k8s.io/v1alpha1} args:{[{token} {-i} {eksCluster-eksCluster-ID}]} command:{aws-iam-authenticator}]}]}]}]}]} has a problem: provider property values must be strings
 
error: an error occurred while advancing the preview
```

**Comment by kevintest711** [comment] 2019-02-20 19:14
/kubernetes-the-prod-way/services/wordpress# pulumi up
Previewing update (wordpress):

     Type                             Name                                 Plan       Info
 +   pulumi:pulumi:Stack              wordpress-wordpress                  create     
 +   ├─ kubernetes:helm.sh:Chart      wpdev                                create     
 >-  ├─ pulumi:pulumi:StackReference  kevintest711/infrastructure/kc-infra  read       
     └─ pulumi:providers:kubernetes   kevintest711/infrastructure/kc-infra             1 error
 
Diagnostics:
  pulumi:providers:kubernetes (kevintest711/infrastructure/kc-infra):
    error: pulumi:providers:kubernetes resource 'kevintest711/infrastructure/kc-ifra's property 'kubeconfig' value {map[apiVersion:{v1} clusters:{[{map[cluster:{map[certificate-authority-data:{CERT-REDACTED} server:{https://something.something.us-east-2.eks.amazonaws.com}]} name:{kubernetes}]}]} contexts:{[{map[context:{map[cluster:{kubernetes} user:{aws}]} name:{aws}]}]} current-context:{aws} kind:{Config} users:{[{map[name:{aws} user:{map[exec:{map[apiVersion:{client.authentication.k8s.io/v1alpha1} args:{[{token} {-i} {eksCluster-eksCluster-123}]} command:{aws-iam-authenticator}]}]}]}]}]} has a problem: provider property values must be strings
 
error: an error occurred while advancing the preview

**Comment by metral** [comment] 2019-02-20 23:02
@adaniline-traderev The kubeconfig comes out as a raw JSON object, so you must convert it to a string to pass to a provider. Try this and see if it works for you:

```
const provider = new k8s.Provider("myKubernetesCluster", {
    kubeconfig: config.kubeconfig.apply(JSON.stringify),
});
```

**Comment by joeduffy** [comment] 2019-03-07 00:46
@metral @hausdorff @lblackstone Should this be closed? Is there anything we can do to improve the diagnostics here?

**Comment by lukehoban** [comment] 2019-03-09 19:59
Closing out, as it seems the error message was actually reasonably clear (the original reporter includes the key part in the title of this bug, and had already identified the probable root cause as part of opening the issue).

There is a reasonable question of whether this property *should* accept an object instead of a string - and that is ultimately related back to https://github.com/pulumi/pulumi/issues/2306 (through a few indirections).

**Closed by lukehoban** 2019-03-09 19:59 UTC
